### PR TITLE
Zephyr 3.5 Update

### PR DESCRIPTION
**Pull request by microfortnight**
Applying necessary changes for the Zephyr 3.5 update described here:
https://zmk.dev/blog/2024/02/09/zephyr-3-5

I did some basic testing and the firmware seems to work just fine.
What I didn't test:
* OLED inversion: My board doesn't have one
* West Flash Support: Requires local build, but I used the GitHub actions.

### CODE REVIEW

**Comment by MangoIV** [comment]
Did you check the job on whether it pulls the correct container?

**Review by MangoIV — APPROVED** [review]
Looks good to me, I will check whether that OLED stuff works on my schiff and if it does I’ll merge. And prepare a release.

**Comment by microfortnight** [comment]
> Did you check the job on whether it pulls the correct container?

Nope, just tried to fixed the build, broken by upstream changes, but seems to work ...

**Comment by MangoIV** [comment]
wait but the build cannot "just break" the container should be pinned.

**Comment by microfortnight** [comment]
Okay, I will check, if I broke the pinned container in my fork .

**Comment by microfortnight** [comment]
Rebased on #9

**Comment by MangoIV** [comment]
sorry I forgot this

**Pull request merged**
